### ISSUE TITLE
Unable to install via pip on g5.xlarge AWS machine on AMI Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.3.0 (Amazon Linux 2) 20240825

### ISSUE THREAD

**Issue by danielepoterti** [leonardodalinky/fpsample#3]
As per the title I am not able to install version 0.3.3 via pip on the AWS machine but only 0.2.0 that doesn't come with bucket_fps_kdline_sampling

**Comment by leonardodalinky** [comment]
May I have the detailed installation error logs?

Also, I am migrating the pre-compiled code into self-compiling PyTorch version in [pytorch_fpsample](https://github.com/leonardodalinky/pytorch_fpsample). If this issue is caused by some problems of the pre-compiled `fpsample` package in PyPI, try this new one as a fast solution. Note that the PyTorch Version only works for CPU mode currently.

**Comment by danielepoterti** [comment]
here is your installation logs:

> pip install fpsample
```
Collecting fpsample
  Downloading fpsample-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Requirement already satisfied: numpy>=1.16.0 in /opt/conda/envs/pytorch/lib/python3.11/site-packages (from fpsample) (1.26.4)
Downloading fpsample-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 45.5 MB/s eta 0:00:00
Installing collected packages: fpsample
Successfully installed fpsample-0.2.0
```
pip install fpsample==0.3.3
```
ERROR: Ignored the following yanked versions: 0.3.0, 0.3.1, 0.3.2
ERROR: Could not find a version that satisfies the requirement fpsample==0.3.3 (from versions: 0.1.0, 0.2.0)
ERROR: No matching distribution found for fpsample==0.3.3
```

I will try the Pytorch version, thank you!

**Comment by leonardodalinky** [comment]
It seems that this is caused by the lagged updates in the package mirrors. And the versions of 0.3.{0,1,2} are yanked because of the potential bugs.

Try to check the package mirror source or install using `pip install -U -i https://pypi.org/simple fpsample`.
